# === STAGE 1: BUILDER ===
FROM node:24-alpine AS builder
WORKDIR /app

# Salin package.json dan package-lock.json untuk menginstal dependensi
COPY package*.json ./
RUN npm install

# Salin seluruh source code aplikasi web-dinamis
COPY . . 

# Lakukan build aplikasi Next.js (menghasilkan folder .next/standalone jika dikonfigurasi)
RUN npm run build


# === STAGE 2: RUNNER (PRODUKSI) ===
FROM node:24-alpine AS runner
WORKDIR /app

# Atur environment variable ke mode production
ENV NODE_ENV=production

# Perbaikan Standalone Next.js:
# Menyalin hasil kompilasi standalone langsung ke root direktori kerja (/app)
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Membuka port internal container
EXPOSE 3000

# Menjalankan aplikasi dari berkas server.js hasil standalone build
CMD ["node", "server.js"]