version: '3.8'

services:
  db-webdinamis:
    image: mariadb:lts
    container_name: web-dinamis-db-webdinamis-1
    environment:
      MARIADB_ROOT_PASSWORD: "password_root_123"
      MARIADB_DATABASE: dbcompro_2388010009
      MARIADB_USER: userwebdinamis_2388010009
      MARIADB_PASSWORD: "passwordwebdinamis123"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_data/dbcompro_2388010009.sql:/docker-entrypoint-initdb.d/dbcompro_2388010009.sql:ro
    restart: always

  container-dinamis:
    image: ${DOCKERHUB_USERNAME}/web-dinamis_2388010009:latest
    container_name: web-dinamis-container-dinamis-1
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_USER: userwebdinamis_2388010009
      DB_PASSWORD: "passwordwebdinamis123"
      DB_NAME: dbcompro_2388010009
      DB_HOST: db-webdinamis
      NEXTAUTH_SECRET: ini-kdkdkdkdkdkkd-hdhdhdhdhdhdh-
      NEXTAUTH_URL: http://18.136.205.99
    depends_on:
      - db-webdinamis

volumes:
  db_data: {}